[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
startupTimeout = 300


[deploy.env]
NODE_ENV = "production" 