[build]
builder = "nixpacks"
buildCommand = "npm run build && npx prisma migrate deploy"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
startupTimeout = 300


[deploy.env]
NODE_ENV = "production" 